# SPDX-License-Identifier: MIT

name: Metadata checker

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    paths:
      - '*.user.js'
      - '*.user.css'
      - 'maintenance/check-metadata.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    name: Check metadata
    runs-on: ubuntu-latest
    steps:
    - name: Fetch source code
      uses: actions/checkout@v4

    - name: Do check metadata
      run:
        ./maintenance/check-metadata.sh
